Stat svc
DZaparov/java-explore-with-me pull request #1
Opened 2024-06-02 16:21 UTC by DZaparov

2024-06-03 06:27 UTC, VadimZharkov commented on pom.xml
> +	<dependencies>
Зависимости из родительского pom лучше убрать, т.к. зависимости в дочерних pom у некоторых модулей будут отличаться. Некоторые модули являются приложением, некоторые просто библиотеками, каким то из них требуется база данных, каким то нет. В общем лучше в каждом модуле сделать свои зависимости, чтобы при сборке не тянулось ничего лишнего от родительского помника.

2024-06-03 06:29 UTC, VadimZharkov commented on main-service/pom.xml
> +    <properties>
А вот свойства (кодировка и версия джавы) у всех модулей будут одинаковые и поэтому имеет смысл вынести в родительский pom.

2024-06-03 06:34 UTC, VadimZharkov commented on stats-service/dto/src/main/java/ru/practicum/ewm/EndpointHit.java
> +@Entity
Под DTO понимают объекты которые служат для передачи данных между слоями приложения и они не являются сущностями и соответственно их не нужно будет сохранять в БД.

2024-06-03 06:35 UTC, VadimZharkov commented on stats-service/server/pom.xml
> +    <properties>
Про св-ва и зависимости см. комменты выше

2024-06-03 06:37 UTC, VadimZharkov requested changes
Можно улучшить.

2024-06-04 12:26 UTC, DZaparov commented on pom.xml
> +	<dependencies>
Зависимости распределены по модулям, где они используются

2024-06-04 12:27 UTC, DZaparov commented on main-service/pom.xml
> +    <properties>
Свойства вынесены в родительский pom

2024-06-04 12:30 UTC, DZaparov commented on stats-service/dto/src/main/java/ru/practicum/ewm/EndpointHit.java
> +@Entity
В модуль сервера статистики добавлена модель Stats, которая маппится с DTO

2024-06-04 12:30 UTC, DZaparov commented on stats-service/server/pom.xml
> +    <properties>
+

2024-06-05 05:18 UTC, VadimZharkov approved these changes

2024-06-05 07:17 UTC, merged